import 'dart:io';
import 'package:ai_chat_bot/features/chat/data/models/message.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class ConversationExporter {
  /// Export conversation as a formatted text file
  static Future<void> exportAsFile(
    List<Message> messages, {
    String? conversationTitle,
  }) async {
    final title = conversationTitle ?? 'Conversation Export';
    final date = DateFormat('yyyy-MM-dd_HH-mm').format(DateTime.now());
    final fileName = 'chat_${title.replaceAll(RegExp(r'\s+'), '_')}_$date.md';

    final content = _formatConversation(messages, title);

    try {
      final directory = await getTemporaryDirectory();
      final file = File('${directory.path}/$fileName');
      await file.writeAsString(content);

      await Share.shareXFiles([
        XFile(file.path),
      ], text: 'Here is my conversation: "$title"');
    } catch (e) {
      // Fallback to text share if file creation fails
      await Share.share(content, subject: 'Conversation Export: $title');
    }
  }

  /// Export conversation as plain text
  static Future<void> exportAsText(
    List<Message> messages, {
    String? conversationTitle,
  }) async {
    final title = conversationTitle ?? 'Conversation Export';
    final content = _formatConversation(messages, title);
    await Share.share(content, subject: 'Conversation Export: $title');
  }

  static String _formatConversation(List<Message> messages, String title) {
    final buffer = StringBuffer();
    buffer.writeln('# $title');
    buffer.writeln(
      'Exported on ${DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())}',
    );
    buffer.writeln('----------------------------------------');
    buffer.writeln();

    // Sort valid messages by timestamp
    final validMessages = messages.where((m) => m.content.isNotEmpty).toList()
      ..sort(
        (a, b) => (a.createdAt ?? DateTime.fromMillisecondsSinceEpoch(0))
            .compareTo(b.createdAt ?? DateTime.fromMillisecondsSinceEpoch(0)),
      );

    for (final message in validMessages) {
      final role = message.isUser ? 'User' : 'AI';
      final date = message.createdAt ?? DateTime.now();
      final time = DateFormat('HH:mm').format(date);

      buffer.writeln('**$role** ($time):');
      buffer.writeln(message.content);
      buffer.writeln();
    }

    buffer.writeln('----------------------------------------');
    buffer.writeln('Generated by AI Chat Bot');

    return buffer.toString();
  }
}
